name: Build main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 16 ]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2.4.0
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.4.0
        with:
          java-version: ${{ matrix.java }}
          cache: 'maven'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml